version: '3'

services:
  db:
    image: postgres
    container_name: postgres-hr
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "hr-"
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: postgres-hr
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - .:/home/app
    depends_on:
      - db
      - redis
